import { useState } from 'react';
import { reports } from '../../data/adminMockData';

export default function Reports() {
  const [filterType, setFilterType] = useState('All');
  const [showGenModal, setShowGenModal] = useState(false);

  const filtered = reports.filter(r => filterType === 'All' || r.type === filterType);

  const academicCount = reports.filter(r => r.type === 'Academic').length;
  const attendanceCount = reports.filter(r => r.type === 'Attendance').length;
  const teacherCount = reports.filter(r => r.type === 'Teacher').length;
  const financialCount = reports.filter(r => r.type === 'Financial').length;

  const typeColors: Record<string, string> = {
    Academic: 'bg-purple-100 text-purple-700',
    Attendance: 'bg-blue-100 text-blue-700',
    Teacher: 'bg-emerald-100 text-emerald-700',
    Financial: 'bg-amber-100 text-amber-700',
  };

  const formatIcons: Record<string, string> = {
    PDF: '📕',
    Excel: '📊',
  };

  return (
    <div className="space-y-6">
      {/* Stats */}
      <div className="grid grid-cols-2 lg:grid-cols-4 gap-4">
        <div className="bg-white rounded-2xl border border-gray-100 shadow-sm p-5">
          <div className="w-10 h-10 bg-purple-50 rounded-xl flex items-center justify-center text-xl mb-3">🎓</div>
          <p className="text-2xl font-bold text-gray-800">{academicCount}</p>
          <p className="text-sm text-gray-500">Academic Reports</p>
        </div>
        <div className="bg-white rounded-2xl border border-gray-100 shadow-sm p-5">
          <div className="w-10 h-10 bg-blue-50 rounded-xl flex items-center justify-center text-xl mb-3">📋</div>
          <p className="text-2xl font-bold text-gray-800">{attendanceCount}</p>
          <p className="text-sm text-gray-500">Attendance Reports</p>
        </div>
        <div className="bg-white rounded-2xl border border-gray-100 shadow-sm p-5">
          <div className="w-10 h-10 bg-emerald-50 rounded-xl flex items-center justify-center text-xl mb-3">👩‍🏫</div>
          <p className="text-2xl font-bold text-gray-800">{teacherCount}</p>
          <p className="text-sm text-gray-500">Teacher Reports</p>
        </div>
        <div className="bg-white rounded-2xl border border-gray-100 shadow-sm p-5">
          <div className="w-10 h-10 bg-amber-50 rounded-xl flex items-center justify-center text-xl mb-3">💰</div>
          <p className="text-2xl font-bold text-gray-800">{financialCount}</p>
          <p className="text-sm text-gray-500">Financial Reports</p>
        </div>
      </div>

      {/* Filters */}
      <div className="bg-white rounded-2xl border border-gray-100 shadow-sm p-5">
        <div className="flex flex-wrap items-end gap-4">
          <div>
            <label className="text-xs font-medium text-gray-500 uppercase tracking-wider">Report Type</label>
            <select value={filterType} onChange={e => setFilterType(e.target.value)}
              className="mt-1 block w-40 px-4 py-2.5 bg-gray-50 border border-gray-200 rounded-xl text-sm focus:ring-2 focus:ring-amber-500 focus:border-transparent outline-none">
              <option value="All">All Types</option><option value="Academic">Academic</option><option value="Attendance">Attendance</option><option value="Teacher">Teacher</option><option value="Financial">Financial</option>
            </select>
          </div>
          <span className="px-3 py-1.5 bg-gray-100 text-gray-600 rounded-lg text-xs font-semibold">{filtered.length} Reports</span>
          <div className="flex-1"></div>
          <button onClick={() => setShowGenModal(true)} className="px-5 py-2.5 bg-amber-600 hover:bg-amber-700 text-white rounded-xl font-medium text-sm transition-colors flex items-center gap-2">
            <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 4v16m8-8H4" /></svg>
            Generate Report
          </button>
        </div>
      </div>

      {/* Reports List */}
      <div className="bg-white rounded-2xl border border-gray-100 shadow-sm overflow-hidden">
        <div className="overflow-x-auto">
          <table className="w-full">
            <thead>
              <tr className="bg-gray-50 border-b border-gray-100">
                <th className="px-5 py-3 text-left text-xs font-semibold text-gray-500 uppercase tracking-wider">Report</th>
                <th className="px-5 py-3 text-center text-xs font-semibold text-gray-500 uppercase tracking-wider">Type</th>
                <th className="px-5 py-3 text-left text-xs font-semibold text-gray-500 uppercase tracking-wider">Generated Date</th>
                <th className="px-5 py-3 text-left text-xs font-semibold text-gray-500 uppercase tracking-wider">Generated By</th>
                <th className="px-5 py-3 text-center text-xs font-semibold text-gray-500 uppercase tracking-wider">Format</th>
                <th className="px-5 py-3 text-center text-xs font-semibold text-gray-500 uppercase tracking-wider">Size</th>
                <th className="px-5 py-3 text-center text-xs font-semibold text-gray-500 uppercase tracking-wider">Status</th>
                <th className="px-5 py-3 text-center text-xs font-semibold text-gray-500 uppercase tracking-wider">Action</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-gray-50">
              {filtered.map(report => (
                <tr key={report.id} className="hover:bg-gray-50 transition-colors">
                  <td className="px-5 py-4">
                    <div className="flex items-center gap-3">
                      <span className="text-2xl">{formatIcons[report.format] || '📄'}</span>
                      <div>
                        <p className="text-sm font-medium text-gray-800">{report.title}</p>
                        <p className="text-xs text-gray-400">{report.id}</p>
                      </div>
                    </div>
                  </td>
                  <td className="px-5 py-4 text-center">
                    <span className={`px-2.5 py-1 rounded-lg text-xs font-semibold ${typeColors[report.type] || 'bg-gray-100 text-gray-700'}`}>{report.type}</span>
                  </td>
                  <td className="px-5 py-4 text-sm text-gray-600">{report.generatedDate}</td>
                  <td className="px-5 py-4 text-sm text-gray-600">{report.generatedBy}</td>
                  <td className="px-5 py-4 text-center">
                    <span className="px-2.5 py-1 bg-gray-100 text-gray-700 rounded-lg text-xs font-medium">{report.format}</span>
                  </td>
                  <td className="px-5 py-4 text-center text-sm text-gray-600">{report.size}</td>
                  <td className="px-5 py-4 text-center">
                    <span className={`px-2.5 py-1 rounded-lg text-xs font-semibold ${
                      report.status === 'Ready' ? 'bg-emerald-100 text-emerald-700' :
                      report.status === 'Generating' ? 'bg-amber-100 text-amber-700' :
                      'bg-red-100 text-red-700'
                    }`}>
                      {report.status === 'Generating' && <span className="inline-block w-1.5 h-1.5 bg-amber-500 rounded-full mr-1 animate-pulse"></span>}
                      {report.status}
                    </span>
                  </td>
                  <td className="px-5 py-4 text-center">
                    {report.status === 'Ready' ? (
                      <div className="flex items-center justify-center gap-1">
                        <button className="px-2.5 py-1.5 bg-blue-50 text-blue-700 rounded-lg text-xs font-medium hover:bg-blue-100 transition-colors">Download</button>
                        <button className="px-2.5 py-1.5 bg-gray-50 text-gray-700 rounded-lg text-xs font-medium hover:bg-gray-100 transition-colors">Preview</button>
                      </div>
                    ) : (
                      <span className="text-xs text-gray-400">-</span>
                    )}
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>

      {/* Report Summary Cards */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        <div className="bg-white rounded-2xl border border-gray-100 shadow-sm p-5">
          <h3 className="font-bold text-gray-800 mb-4">📊 Reports by Type</h3>
          <div className="space-y-3">
            {['Academic', 'Attendance', 'Teacher', 'Financial'].map(type => {
              const count = reports.filter(r => r.type === type).length;
              const pct = Math.round((count / reports.length) * 100);
              return (
                <div key={type}>
                  <div className="flex items-center justify-between mb-1.5">
                    <span className="text-sm text-gray-600">{type}</span>
                    <span className="text-sm font-medium text-gray-700">{count} ({pct}%)</span>
                  </div>
                  <div className="w-full bg-gray-100 rounded-full h-2.5">
                    <div className={`h-2.5 rounded-full ${type === 'Academic' ? 'bg-purple-500' : type === 'Attendance' ? 'bg-blue-500' : type === 'Teacher' ? 'bg-emerald-500' : 'bg-amber-500'}`} style={{ width: `${pct}%` }}></div>
                  </div>
                </div>
              );
            })}
          </div>
        </div>

        <div className="bg-white rounded-2xl border border-gray-100 shadow-sm p-5">
          <h3 className="font-bold text-gray-800 mb-4">📅 Recent Activity</h3>
          <div className="space-y-3">
            {reports.slice(0, 5).map(report => (
              <div key={report.id} className="flex items-center gap-3 p-3 bg-gray-50 rounded-xl">
                <span className="text-xl">{formatIcons[report.format] || '📄'}</span>
                <div className="flex-1 min-w-0">
                  <p className="text-sm font-medium text-gray-800 truncate">{report.title}</p>
                  <p className="text-xs text-gray-500">{report.generatedDate} by {report.generatedBy}</p>
                </div>
                <span className={`px-2 py-0.5 rounded text-[10px] font-semibold ${report.status === 'Ready' ? 'bg-emerald-100 text-emerald-700' : 'bg-amber-100 text-amber-700'}`}>{report.status}</span>
              </div>
            ))}
          </div>
        </div>
      </div>

      {/* Generate Report Modal */}
      {showGenModal && (
        <div className="fixed inset-0 bg-black/50 z-50 flex items-center justify-center p-4" onClick={() => setShowGenModal(false)}>
          <div className="bg-white rounded-2xl max-w-lg w-full shadow-2xl" onClick={e => e.stopPropagation()}>
            <div className="p-6 border-b border-gray-100 bg-gradient-to-r from-amber-50 to-amber-100 rounded-t-2xl">
              <h3 className="text-lg font-bold text-gray-800">Generate New Report</h3>
              <p className="text-sm text-gray-500">Select the report type and parameters</p>
            </div>
            <div className="p-6 space-y-4">
              <div>
                <label className="text-xs text-gray-500 font-medium">Report Title</label>
                <input className="mt-1 w-full px-3 py-2 bg-gray-50 border border-gray-200 rounded-lg text-sm outline-none focus:ring-2 focus:ring-amber-500" placeholder="Enter report title" />
              </div>
              <div className="grid grid-cols-2 gap-4">
                <div>
                  <label className="text-xs text-gray-500 font-medium">Report Type</label>
                  <select className="mt-1 w-full px-3 py-2 bg-gray-50 border border-gray-200 rounded-lg text-sm outline-none focus:ring-2 focus:ring-amber-500">
                    <option>Academic</option><option>Attendance</option><option>Teacher</option><option>Financial</option>
                  </select>
                </div>
                <div>
                  <label className="text-xs text-gray-500 font-medium">Format</label>
                  <select className="mt-1 w-full px-3 py-2 bg-gray-50 border border-gray-200 rounded-lg text-sm outline-none focus:ring-2 focus:ring-amber-500">
                    <option>PDF</option><option>Excel</option>
                  </select>
                </div>
              </div>
              <div className="grid grid-cols-2 gap-4">
                <div>
                  <label className="text-xs text-gray-500 font-medium">Date Range Start</label>
                  <input type="date" className="mt-1 w-full px-3 py-2 bg-gray-50 border border-gray-200 rounded-lg text-sm outline-none focus:ring-2 focus:ring-amber-500" />
                </div>
                <div>
                  <label className="text-xs text-gray-500 font-medium">Date Range End</label>
                  <input type="date" className="mt-1 w-full px-3 py-2 bg-gray-50 border border-gray-200 rounded-lg text-sm outline-none focus:ring-2 focus:ring-amber-500" />
                </div>
              </div>
              <div className="flex gap-3 pt-2">
                <button onClick={() => setShowGenModal(false)} className="flex-1 px-4 py-2.5 bg-amber-600 hover:bg-amber-700 text-white rounded-xl font-medium text-sm transition-colors">Generate Report</button>
                <button onClick={() => setShowGenModal(false)} className="flex-1 px-4 py-2.5 bg-gray-100 text-gray-700 rounded-xl font-medium text-sm hover:bg-gray-200 transition-colors">Cancel</button>
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
